version: '3.9'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  webapp:
    image: ghcr.io/mcforse/docker-compose-tasklist-app:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      - SERVER_PORT=${WEB_PORT}
      - SPRING_DATASOURCE_URL=${POSTGRES_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
